Assignment_1/Controllers/FriendController.cs
using Assignment_1.ActionFilters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_1.Controllers
{
    [LoginFilter]
    [ProfileNeeded]
    public class FriendController : Controller
    {
        Models.ClientsDBEntities db = new Models.ClientsDBEntities();
        // GET: Friend
        public ActionResult Index()
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            Models.client theClient = db.clients.SingleOrDefault(c => c.person_id == id);
            return View(theClient);
        }

        public ActionResult Search(string data)
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            IEnumerable<Models.client> result = db.clients.Where(c => (c.first_name + " " + c.last_name).Contains(data));
            return View("SearchResults", result);
        }

        // GET: Friend/New
        public ActionResult New(int id)
        {
            ViewBag.id = id;
            ViewBag.name = db.clients.SingleOrDefault(c => c.person_id == id).first_name + " " +
                           db.clients.SingleOrDefault(c => c.person_id == id).last_name;
            return View();
        }

        // POST: Friend/New
        [HttpPost]
        public ActionResult New(int id, FormCollection collection)
        {
            try
            {
                int idd = Int32.Parse(Session["account_id"].ToString());
                Models.friendlink newRequest = new Models.friendlink()
                {
                    requester = idd,
                    requested = id,
                    status = collection["status"],
                    timestamp = DateTime.Now,
                    read = 0,
                    approved = 0
                };
                db.friendlinks.Add(newRequest);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }
            catch {
                return View();
            }
        }

        public ActionResult Accept(int id)
        {
            int reqsted = Int32.Parse(Session["account_id"].ToString());
            Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requester == id && f.requested == reqsted);
            if (theFriend.approved == 1) {
                return Content("Already Friends");
            }
            theFriend.read = 1;
            theFriend.approved = 1;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            int reqsted = Int32.Parse(Session["account_id"].ToString());
            Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requester == id && f.requested == reqsted);
            db.friendlinks.Remove(theFriend);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Cancel(int id)
        {
            int reqsted = Int32.Parse(Session["account_id"].ToString());
            Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requested == id && f.requester == reqsted);
            db.friendlinks.Remove(theFriend);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Friend/Edit/5
        public ActionResult Edit(int id)
        {
            Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requested == id);
            return View(theFriend);
        }

        // POST: Friend/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                int idd = Int32.Parse(Session["account_id"].ToString());
                Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requested == id);
                theFriend.status = collection["status"];

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Friend/Remove/5
        public ActionResult Remove(int id)
        {
            int idd = Int32.Parse(Session["account_id"].ToString());
            Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requested == id && f.requester == idd || f.requested == idd && f.requester == id);
            return View(theFriend);
        }

        // POST: Friend/Remove/5
        [HttpPost]
        public ActionResult Remove(int id, FormCollection collection)
        {
            try
            {
                int idd = Int32.Parse(Session["account_id"].ToString());
                Models.friendlink theFriend = db.friendlinks.SingleOrDefault(f => f.requested == id && f.requester == idd || f.requested == idd && f.requester == id);
                db.friendlinks.Remove(theFriend);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assignment_1/Controllers/LoginController.cs
using Assignment_1.ActionFilters;
using Assignment_1.Content;
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace Assignment_1.Controllers
{
    public class LoginController : Controller
    {
        Models.ClientsDBEntities db = new Models.ClientsDBEntities();
        // GET: Login
        [LoggedIn]
        public ActionResult Index()
        {
            return View();
        }

        [LoggedIn]
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            string username = collection["username"];
            Models.account theAccount = db.accounts.SingleOrDefault(u => u.username.Equals(username));
            if (theAccount != null &&
                Crypto.VerifyHashedPassword(theAccount.password_hash, collection["password_hash"]))
            {
                Session["profile_id"] = theAccount.profile_id;
                if (theAccount.secret != null)
                {
                    return RedirectToAction("Validation");
                }
                else{
                    Session["account_id"] = theAccount.account_id;
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.error = 1;
                return View();
            }
        }

        [LoggedIn]
        public ActionResult Validation()
        {
            if (Session["profile_id"] == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [LoggedIn]
        [HttpPost]
        public ActionResult Validation(FormCollection collection)
        {
            if (Session["profile_id"] == null) {
                return RedirectToAction("Index");
            }
            int id = Int32.Parse(Session["profile_id"].ToString());
            Models.account theAccount = db.accounts.SingleOrDefault(a => a.account_id == id);
            if (theAccount != null)
            {
                if (theAccount.secret != null)
                {
                    Totp totp = new Totp(theAccount.secret);
                    string theCode = totp.AuthenticationCode;
                    if (theCode.Equals(collection["secret"]))
                    {
                        Session["account_id"] = theAccount.account_id;
                        return RedirectToAction("Index", "Home");
                    }
                }
                ViewBag.error = 1;
                return View();
            }
            else
            {
                ViewBag.error = "An Error has occured!";
                return View();
            }
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index");
        }

        public static Random random = new Random();

        private static string RandomBase32String(int lenght) {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
            return new string(Enumerable.Repeat(chars, lenght).Select(s => s[random.Next(s.Length)]).ToArray());
        }

        // GET: ChangePassword/
        [LoginFilter]
        public ActionResult ChangePassword()
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            ViewBag.id = id;
            ViewBag.name = db.clients.SingleOrDefault(c => c.person_id == id).first_name + " " +
                           db.clients.SingleOrDefault(c => c.person_id == id).last_name;
            return View();
        }

        // POST: Login/ChangePassword
        [HttpPost]
        public ActionResult ChangePassword(FormCollection collection)
        {
            try
            {
                int id = Int32.Parse(Session["account_id"].ToString());
                Models.account theAccount = db.accounts.SingleOrDefault(c => c.account_id == id);
                if (theAccount != null &&
                    Crypto.VerifyHashedPassword(theAccount.password_hash, collection["password_hash"]))
                {
                    theAccount.password_hash = Crypto.HashPassword(collection["password_hash_new"]);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Profile", new { id = theAccount.account_id });
                }
                else
                {
                    ViewBag.error = 1;
                    return View();
                }
            }
            catch (System.Data.Entity.Validation.DbEntityValidationException dbEx)
            {
                Exception raise = dbEx;
                foreach (var validationErrors in dbEx.EntityValidationErrors)
                {
                    foreach (var validationError in validationErrors.ValidationErrors)
                    {
                        string message = string.Format("{0}:{1}",
                            validationErrors.Entry.Entity.ToString(),
                            validationError.ErrorMessage);
                        // raise a new exception nesting
                        // the current instance as InnerException
                        raise = new InvalidOperationException(message, raise);
                    }
                }
                throw raise;
            }
        }

        [LoggedIn]
        public ActionResult Register()
        {
            string secret = RandomBase32String(16);
            string otpauth = "otpauth://totp/User:E-Commerce?secret="+ secret +"&issuer=SocialNetwork_";

            //Generates a QR code
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(otpauth, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);
            ImageConverter converter = new ImageConverter();
            ViewBag.QRCode = (byte[])converter.ConvertTo(qrCodeImage, typeof(byte[]));
            Session["secret"] = secret;

            return View();
        }

        // POST: Login/Register
        [LoggedIn]
        [HttpPost]
        public ActionResult Register(FormCollection collection)
        {
            try
            {
                string secret = Session["secret"].ToString();
                Totp totp = new Totp(secret);

                String theSecret = null;
                if (totp.AuthenticationCode.Equals(collection["validation"].Trim())) {
                    //add secret to user account
                    theSecret = secret;
                }

                string username = collection["username"];
                Models.account theAccount = db.accounts.SingleOrDefault(u => u.username.Equals(username));
                if (theAccount != null)
                {
                    return RedirectToAction("Register");
                }

                Models.account newAccount = new Models.account()
                {
                    username = collection["username"],
                    password_hash = Crypto.HashPassword(collection["password_hash"]),
                    secret = theSecret
                };

                db.accounts.Add(newAccount);
                db.SaveChanges();
                Session["account_id"] = newAccount.account_id;
                return RedirectToAction("Create", "Profile");
            }
            catch {
                return View();
            }
        }
    }
}

Assignment_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min-lumen.css" rel="stylesheet" type="text/css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            @if (Session["account_id"] != null)
            {
                @Html.ActionLink("Social Network_", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            }
            else
            {
                @Html.ActionLink("Social Network_", "Index", "Login", new { area = "" }, new { @class = "navbar-brand" })
            }

            <div class="collapse navbar-collapse" id="navbarColor01">
                @if (Session["account_id"] != null)
                {
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            @Html.ActionLink("Profile", "Details", "Profile", new { id = Session["account_id"] }, new { @class = "navbar-brand" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Friends", "Index", "Friend", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Messages", "index", "Message", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Login", new { area = "" }, new { @class = "navbar-brand" })
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" method="get" action="/Friend/Search">
                        <input class="form-control mr-sm-2" type="text" name="data" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                }
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - George Christeas, Zubair Janjua</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>