Assignment_1/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_1.Controllers
{
    public class CommentController : Controller
    {
        Models.ClientsDBEntities db = new Models.ClientsDBEntities();
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }

        // GET: Comment/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult LikeComment(int id)
        {
            int liker = Int32.Parse(Session["account_id"].ToString());
            Models.comment_likes newCommentLike = new Models.comment_likes()
            {
                person_id = liker,
                comment_id = id,
                timestamp = DateTime.Now,
                read = 0
            };
            db.comment_likes.Add(newCommentLike);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        public ActionResult UnlikeComment(int id)
        {
            int liker = Int32.Parse(Session["account_id"].ToString());
            Models.comment_likes theLike = db.comment_likes.SingleOrDefault(l => l.comment_id == id && l.person_id == liker);
            db.comment_likes.Remove(theLike);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        // GET: Comment/Create
        public ActionResult Create(int id)
        {
            int sender = Int32.Parse(Session["account_id"].ToString());
            ViewBag.id = id;
            return View();
        }

        // POST: Comment/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection)
        {
            int sender = Int32.Parse(Session["account_id"].ToString());
            try
            {
                Models.comment newComment = new Models.comment()
                {
                    picture_id = id,
                    profile_id = sender,
                    comment_text = collection["comment_text"],
                    timestamp = DateTime.Now,
                    read = 0
                };
                db.comments.Add(newComment);
                db.SaveChanges();

                return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Edit/5
        public ActionResult Edit(int id)
        {
            Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);
            if (theComment.profile_id != Int32.Parse(Session["account_id"].ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(theComment);
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);
                theComment.comment_text = collection["comment_text"];
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
        
        // GET: Comment/Delete/5
        public ActionResult Delete(int id)
        {
            Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);
            if (theComment.profile_id != Int32.Parse(Session["account_id"].ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            IEnumerable<Models.comment_likes> theLikes = db.comment_likes.Where(c => c.comment_id == id);
            foreach (Models.comment_likes x in theLikes) {
                db.comment_likes.Remove(x);
            }
            db.comments.Remove(theComment);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }
    }
}

Assignment_1/Controllers/HomeController.cs
using Assignment_1.ActionFilters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Assignment_1.Controllers
{
    [LoginFilter]
    public class HomeController : Controller
    {
        Models.ClientsDBEntities db = new Models.ClientsDBEntities();
        // GET: Picture
        public ActionResult Index()
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            ViewBag.id = id;
            var thePictures = db.clients.SingleOrDefault(c => c.person_id == id);
            return View(thePictures);
        }

        public ActionResult Like(int id)
        {
            int liker = Int32.Parse(Session["account_id"].ToString());
            Models.like newLike = new Models.like() {
                person_id = liker,
                picture_id = id,
                timestamp = DateTime.Now,
                read = 0
            };
            db.likes.Add(newLike);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        public ActionResult Unlike(int id)
        {
            int liker = Int32.Parse(Session["account_id"].ToString());
            Models.like theLike = db.likes.SingleOrDefault(l => l.picture_id == id && l.person_id == liker);
            db.likes.Remove(theLike);
            db.SaveChanges();
            return Redirect(ControllerContext.HttpContext.Request.UrlReferrer.ToString());
        }

        public ActionResult HomeList()
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            ViewBag.id = id;
            IEnumerable<Models.picture> thePictures = db.pictures.Where(p => p.person_id == id);
            return View(thePictures);
        }
    // GET: Picture/Create
        public ActionResult Create()
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            ViewBag.id = id;
            return View();
        }
      
        // POST: Picture/Create/5
        [HttpPost]
        public ActionResult Create(FormCollection collection, HttpPostedFileBase newPicture)
        {
            int id = Int32.Parse(Session["account_id"].ToString());
            try
            {
                string[] type = { "image/gif", "image/png", "image/jpeg" };

                if (newPicture != null && newPicture.ContentLength > 0 && type.Contains(newPicture.ContentType))
                {
                    Guid g = Guid.NewGuid();
                    string filename = g + Path.GetExtension(newPicture.FileName);
                    string path = Server.MapPath("~/Images/");
                    path = Path.Combine(path, filename);
                    newPicture.SaveAs(path);

                    Models.picture newPic = new Models.picture()
                    {
                        caption = collection["caption"],
                        time = collection["time"],
                        location = collection["location"],
                        relative_path = filename,
                        person_id = id
                    };
                    
                    db.pictures.Add(newPic);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Edit/5
        public ActionResult Edit(int id)
        {
            Models.picture thePicture = db.pictures.SingleOrDefault(p => p.picture_id == id);
            if (thePicture.person_id != Int32.Parse(Session["account_id"].ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(thePicture);
        }

        // POST: Picture/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                Models.picture thePicture = db.pictures.SingleOrDefault(p => p.picture_id == id);
                thePicture.caption = collection["caption"];
                thePicture.relative_path = collection["relative_path"];
                thePicture.time = collection["time"];
                thePicture.location = collection["location"];

                db.SaveChanges();
                return RedirectToAction("Index", new { id = thePicture.person_id});
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Delete/5
        public ActionResult Delete(int id)
        {
            Models.picture thePicture = db.pictures.SingleOrDefault(p => p.picture_id == id);
            if (thePicture.person_id != Int32.Parse(Session["account_id"].ToString()))
            {
                return RedirectToAction("Index", "Home");
            }
            return View(thePicture);
        }

        // POST: Picture/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                string path = Server.MapPath("~/Images/");
                Models.picture thePicture = db.pictures.SingleOrDefault(p => p.picture_id == id);
                path = Path.Combine(path, thePicture.relative_path);
                System.IO.File.Delete(path);

                db.pictures.Remove(thePicture);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Assignment_1/Views/Home/Create.cshtml
@model Assignment_1.Models.picture

@{
    ViewBag.Title = "Upload a Picture";
}

@using (Html.BeginForm("Create", "Home", FormMethod.Post, new { enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div>
            <div class="container col-md-7">
                <div class="card mb-3">
                    <h3 class="card-header">Upload a new Picture</h3>
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.caption, htmlAttributes: new { @class = "control-label" })
                            @Html.EditorFor(model => model.caption, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.Label("Image", new { @class = "control-label" })
                            <div class="input-group">
                                <div class="custom-file">
                                    <input type="file" name="newPicture" class="custom-file-input text-danger" />
                                    <label class="custom-file-label" for="inputGroupFile02">Choose image</label>
                                    @Html.ValidationMessageFor(model => model.relative_path, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.time, new { @class = "control-label" })
                            @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.location, new { @class = "control-label" })
                            @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        <div class="form-group">
                            <div class="col-md-offset-2">
                                <input type="submit" value="Upload" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Back to Home", "Index")
    </div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Assignment_1/Views/Home/Delete.cshtml
@model Assignment_1.Models.picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this picture?</h3>
<div>
    <hr />
    <dl class="dl-horizontal col-md-10">
        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.relative_path)" height="150" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.relative_path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.relative_path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to Home", "Index")
        </div>
    }
</div>

Assignment_1/Views/Home/Details.cshtml
@model Assignment_1.Models.picture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>
        @Html.DisplayFor(model => model.client.first_name)
        @Html.DisplayFor(model => model.client.last_name)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.relative_path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.relative_path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayName("Preview")
        </dt>

        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.relative_path)" height="100" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to Picture List", "Index", new { id = Model.person_id }) |
    @Html.ActionLink("Edit", "Edit", new { id = Model.picture_id }) |
    @Html.ActionLink("Upload Picture", "Create", new { id = Model.person_id }) |
    @Html.ActionLink("View Client", "Details", "Home", new { id = Model.client.person_id }, null)
</p>

Assignment_1/Views/Home/Edit.cshtml
@model Assignment_1.Models.picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>
            @Html.DisplayFor(model => model.client.first_name)
            @Html.DisplayFor(model => model.client.last_name)
        </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.picture_id)
        
        <div class="form-group">
            @Html.LabelFor(model => model.caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.caption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.relative_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.relative_path, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.relative_path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Picture", "Index", "Home")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Assignment_1/Views/Home/HomeList.cshtml
@model IEnumerable<Assignment_1.Models.picture>

@foreach (var item in Model)
{

    <div>
        <div class="container col-md-7 col-md-offset-3">
            <div class="card mb-3">
                <h3 class="card-header">
                    @Html.DisplayFor(modelItem => item.caption)
                    @if (item.person_id == Int32.Parse(Session["account_id"].ToString())) {
                        <div class="btn-group float-right" role="group" aria-label="Button group with nested dropdown">
                        @Html.ActionLink("Edit", "Edit", "Home", new {id = item.picture_id}, new { @class = "btn btn-primary" })
                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="@Url.Action("Delete", "Home", new {id = item.picture_id })">Delete</a>
                            </div>
                        </div>
                    </div>
                    }
                </h3>
                <img src="/Images/@Html.DisplayFor(modelItem => item.relative_path)" style="width:100%" class="mx-auto d-block" />
                @if (item.likes.SingleOrDefault(l => l.picture_id == item.picture_id && l.person_id == Int32.Parse(Session["account_id"].ToString())) == null)
                {
                    <button onclick="location.href='@Url.Action("Like", "Home", new {id = item.picture_id })'" class="btn btn-outline-info"><i class="fa fa-heart" aria-hidden="true"></i> Like</button>
                }
                else
                {
                    <button onclick="location.href='@Url.Action("Unlike", "Home", new {id = item.picture_id })'" class="btn btn-info"> <i class="fa fa-heart" aria-hidden="true"></i> Unlike</button>
                }
                <div class="card-footer text-muted">
                    @Html.DisplayFor(modelItem => item.time) in <b>@Html.DisplayFor(modelItem => item.location)</b>
                </div>

                @Html.Partial("../Comment/Comments", item.comments.Where(c => c.picture_id == item.picture_id))

                <div>
                    @using (Html.BeginForm("Create", "Comment", new { id = item.picture_id }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="input-group">
                            <input type="text" class="form-control" name="comment_text" placeholder="Comment" aria-label="Comment" aria-describedby="basic-addon2">

                            <div class="input-group-append">
                                <input type="submit" value="Post" class="btn btn-outline-primary" />
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
}

Assignment_1/Views/Home/Index.cshtml
@model Assignment_1.Models.client

@{
    ViewBag.Title = "Home";
}
<h2>Wall</h2>

@Html.ActionLink("Upload New Picture", "Create", "Home", new { @class = "btn btn-primary" })

@{
    int id = int.Parse(Session["account_id"].ToString());
    var friends = Model.friendlinks.Where(f => f.requester == id).Select(f=>f.requested).Union(Model.friendlinks1.Where(f => f.requested == id).Select(f => f.requester));
}

<hr />
@Html.Partial("HomeList", Model.pictures.Where(p => friends.Contains(p.person_id) || p.person_id == id))